# Generated by Django 5.0.14 on 2026-08-05 02:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Codigo')),
                ('titulo', models.CharField(max_length=140, verbose_name='Titulo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('origen', models.CharField(choices=[('IMAGEN', 'Imagen subida'), ('VIDEO', 'Video subido'), ('FOTO_CAMARA', 'Foto tomada con la camara'), ('VIDEO_CAMARA', 'Video grabado con la camara'), ('VIVO', 'Deteccion en vivo')], default='IMAGEN', max_length=14, verbose_name='Origen')),
                ('archivo', models.FileField(upload_to='analisis/originales/%Y/%m/', verbose_name='Archivo analizado')),
                ('archivo_resultado', models.FileField(blank=True, null=True, upload_to='analisis/resultados/%Y/%m/', verbose_name='Archivo con detecciones')),
                ('direccion_referencia', models.CharField(blank=True, max_length=200, verbose_name='Direccion / referencia')),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitud')),
                ('procesado', models.BooleanField(default=False, verbose_name='Procesado por IA')),
                ('error_proceso', models.TextField(blank=True, verbose_name='Error de proceso')),
                ('tiempo_proceso', models.FloatField(default=0.0, verbose_name='Tiempo de proceso (s)')),
                ('frames_analizados', models.PositiveIntegerField(default=0, verbose_name='Cuadros analizados')),
                ('total_detecciones', models.PositiveIntegerField(default=0, verbose_name='Total de danos')),
                ('total_baches', models.PositiveIntegerField(default=0, verbose_name='Baches')),
                ('total_grietas', models.PositiveIntegerField(default=0, verbose_name='Grietas')),
                ('sev_baja', models.PositiveIntegerField(default=0, verbose_name='Severidad baja')),
                ('sev_media', models.PositiveIntegerField(default=0, verbose_name='Severidad media')),
                ('sev_alta', models.PositiveIntegerField(default=0, verbose_name='Severidad alta')),
                ('sev_critica', models.PositiveIntegerField(default=0, verbose_name='Severidad critica')),
                ('severidad_maxima', models.CharField(blank=True, choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Critica')], max_length=10, verbose_name='Severidad maxima')),
                ('severidad_predominante', models.CharField(blank=True, choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Critica')], max_length=10, verbose_name='Severidad predominante')),
                ('confianza_promedio', models.FloatField(default=0.0, verbose_name='Confianza promedio')),
                ('area_danada_pct', models.FloatField(default=0.0, verbose_name='Area danada (%)')),
            ],
            options={
                'verbose_name': 'Analisis',
                'verbose_name_plural': 'Analisis',
                'db_table': 'analisis',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Bache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(choices=[('pothole', 'Bache'), ('crack', 'Grieta')], max_length=20, verbose_name='Tipo de dano')),
                ('severidad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Critica')], max_length=10, verbose_name='Severidad')),
                ('confianza', models.FloatField(verbose_name='Confianza')),
                ('x1', models.FloatField(verbose_name='X1')),
                ('y1', models.FloatField(verbose_name='Y1')),
                ('x2', models.FloatField(verbose_name='X2')),
                ('y2', models.FloatField(verbose_name='Y2')),
                ('area_relativa', models.FloatField(default=0.0, verbose_name='Area relativa')),
                ('frame', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cuadro')),
                ('segundo', models.FloatField(blank=True, null=True, verbose_name='Segundo')),
                ('detectado_en', models.DateTimeField(auto_now_add=True, verbose_name='Detectado en')),
            ],
            options={
                'verbose_name': 'Bache detectado',
                'verbose_name_plural': 'Baches detectados',
                'db_table': 'bache',
                'ordering': ['-confianza'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('ciudad', models.CharField(choices=[('JULIACA', 'Juliaca'), ('PUNO', 'Puno')], max_length=10, verbose_name='Ciudad')),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitud')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripcion')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'db_table': 'zona',
                'ordering': ['ciudad', 'nombre'],
            },
        ),
    ]
