# Generated by Django 5.0.14 on 2026-08-05 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analisis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to=settings.AUTH_USER_MODEL, verbose_name='Analizado por'),
        ),
        migrations.AddField(
            model_name='bache',
            name='analisis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baches', to='analisis.analisis', verbose_name='Analisis'),
        ),
        migrations.AddConstraint(
            model_name='zona',
            constraint=models.UniqueConstraint(fields=('ciudad', 'nombre'), name='zona_unica_por_ciudad'),
        ),
        migrations.AddField(
            model_name='analisis',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analisis', to='analisis.zona', verbose_name='Zona'),
        ),
        migrations.AddIndex(
            model_name='bache',
            index=models.Index(fields=['clase'], name='bache_clase_d270d0_idx'),
        ),
        migrations.AddIndex(
            model_name='bache',
            index=models.Index(fields=['severidad'], name='bache_severid_2a665f_idx'),
        ),
        migrations.AddIndex(
            model_name='analisis',
            index=models.Index(fields=['severidad_maxima'], name='analisis_severid_85c2c9_idx'),
        ),
        migrations.AddIndex(
            model_name='analisis',
            index=models.Index(fields=['origen'], name='analisis_origen_488829_idx'),
        ),
        migrations.AddIndex(
            model_name='analisis',
            index=models.Index(fields=['-creado_en'], name='analisis_creado__a2df17_idx'),
        ),
    ]
